spring.application.name=demo
# src/main/resources/application.properties

# 1. 資料庫連線設定
spring.datasource.url=jdbc:mysql://localhost:3307/auth_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=auth_user
spring.datasource.password=auth_password
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# 2. JPA / Hibernate 設定
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
# update: 自動根據 Entity 建立或更新資料表 (開發時好用)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# 3. LINE Login 設定 (本機測試用)
# 請填入你的真實 ID 和 Secret
LINE_CHANNEL_ID=2008702907
LINE_CHANNEL_SECRET=9cf2abf8bae6b442693d357b33b236fe
LINE_CALLBACK_URL=http://localhost:5173/callback


google.client-id: 284686089758-27d4lrnvokk1m5va8v7qklveep2pfept.apps.googleusercontent.com
google.client-secret: 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
google.token-uri: https://oauth2.googleapis.com/token
google.user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo


# 4. Facebook Login 設定
facebook.app-id=878235381396063
facebook.app-secret=c188accef8ab25aaac8a8bed8a5a16c6
# 雖然前端會傳 redirectUri，但這個是用來讓後端參考或驗證的預設值
facebook.redirect-uri=http://localhost:5173/callback
facebook.token-uri=https://graph.facebook.com/v19.0/oauth/access_token
facebook.user-info-uri=https://graph.facebook.com/me